config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    resources :conferences, :defaults => { :format => 'json' }
    resources :events, :defaults => { :format => 'json' } do
      collection do
        post 'update_promoted'
        post 'update_view_counts'
      end
    end
    resources :recordings, :defaults => { :format => 'json' }
    resources :news, :defaults => { :format => 'json' }
  end

  namespace :public do
    get :index, path: '/', defaults: { format: 'json' }
    get :oembed
    resources :conferences, only: [:index, :show], defaults: { format: 'json' }
    constraints(id: %r'[^/]+') do
      resources :events, only: %i(index show), defaults: { format: 'json' } do
        get :search, defaults: { format: 'json' }, on: :collection
      end
    end
    resources :recordings, only: %i(index show), defaults: { format: 'json' } do
      collection do
        post 'count'
      end
    end
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  get '/content/*path', to: 'content#load'

  scope module: 'frontend' do
    root to: 'home#index'
    if Rails.env.production?
      get '404', to: 'home#page_not_found'
    end
    get '/about', to: 'home#about'
    get '/impressum', to: 'home#impressum'
    get '/agb', to: 'home#agb'
    get '/datenschutz', to: 'home#datenschutz'
    get '/search', to: 'search#index'
    get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

    get '/group_event', to: 'account#group'
    get '/library', to: 'account#library'
    get '/settings', to: 'account#settings'
    get '/settings/gdpr-download', to: 'account#gdpr_download'
    get '/settings/blocks', to: 'account#blocks'

    get '/v/:slug', to: 'events#show', as: :event, :constraints => { slug: %r'[^/]+' }
    get '/postroll/:slug', to: 'events#postroll', as: :postroll, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/playlist', to: 'events#playlist_conference', as: :playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/audio', to: 'events#audio_playlist_conference', as: :audio_playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/related', to: 'events#playlist_related', as: :playlist_related, :constraints => { slug: %r'[^/]+' }

    get '/g/:slug', to: 'group_event#show', :constraints => { slug: %r'[^/]+' }

    get '/c/:acronym', to: 'conferences#show', as: :conference

    get '/a', to: 'conferences#all', as: :all_conferences
    get '/b', to: 'conferences#browse', as: :browse_start
    get '/b/*slug', to: 'conferences#browse', as: :browse

    get '/recent', to: 'recent#index'
    get '/popular', to: 'popular#index'

    get '/tags/:tag', to: 'tags#show', as: :tag

    get '/purchase' => 'purchase#execute'

    get '/block' => 'block#getblocks'

    get '/moderation/:id/mute', to: 'moderation#mute_menu', as: :mute_menu, :constraints => { id: %r'[^/]+' }
    get '/moderation/:id/context', to: 'moderation#context', as: :context, :constraints => { id: %r'[^/]+' }
    match '/moderation/:id/unmute', to: 'moderation#unmute_menu', as: :unmute_menu, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/approve', to: 'moderation#approve', as: :approve, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/delete', to: 'moderation#delete', as: :delete, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/mute', to: 'moderation#mute', as: :mute, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/join_group', to: 'group_event#join', as: :join, :via => :post

    resources :event_message, :only => [:create]
    resources :purchase, :only => [:create]
    resources :message_report, :only => [:create]
    resources :block, :only => [:create, :destroy]
    resources :group_event, :only => [:create]

  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApiController
  protect_from_forgery except: %i(create update_promoted)
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # POST /api/events.json
  def index
    @events = Event.all
  end

  # GET /api/events/1.json
  # GET /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def show
  end

  # GET /api/events/new
  def new
    @event = Event.new
  end

  # GET /api/events/1/edit
  # GET /api/events/654331ae-1710-42e5-bdf4-65a03a80c614/edit
  def edit
  end

  # POST /api/events.json
  def create
    acronym = params['acronym']
    conference = Conference.find_by! acronym: acronym
    @event = conference.events.build event_params

    respond_to do |format|
      if create_event(params)
        format.json { render json: @event, status: :created }
      else
        Rails.logger.info("JSON: failed to create event: #{@event.errors.inspect}")
        format.json { render json: @event.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/events/1.json
  # PATCH/PUT /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/events/1.json
  # DELETE /api/events/654331ae-1710-42e5-bdf4-65a03a80c614.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def update_promoted
    Event.update_promoted_from_view_count
    render json: { status: 'ok' }
  end

  def update_view_counts
    Event.update_view_counts
    render json: { status: 'ok' }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    if params[:id] =~ /\A[0-9]+\z/
      @event = Event.find(params[:id])
    else
      @event = Event.find_by(guid: params[:id])
    end
  end

  def create_event(params)
    @event.transaction do
      @event.release_date = Time.now unless @event.release_date
      @event.set_image_filenames(params[:thumb_url], params[:poster_url], params[:timeline_url], params[:thumbnails_url])
      return @event.save
    end
    false
  end

  def event_params
    params.require(:event).permit(:guid, :slug,
      :title, :subtitle, :link,
      :original_language,
      :thumb_filename, :poster_filename, :timeline_filename, :thumbnails_filename,
      :conference_id,
      :metadata,
      :description, :date,
      { persons: [] }, { tags: [] },
      :promoted, :release_date)
  end
end

app/controllers/frontend/account_controller.rb
module Frontend
  class AccountController < FrontendController
    before_action :authenticate_user!

    #GET /settings/blocks
    def blocks
      @blocks = Block.where(user_id: current_user.id)
      respond_to { |format| format.html }
    end

    #GET /settings/gdpr-download
    def gdpr_download
      send_data current_user.to_csv, filename: "#{current_user.name}-#{Date.today}.csv", :type => "text/csv", :disposition => "attachment"
    end

    #GET /library
    def library
      @events = Frontend::Event.joins("
INNER JOIN purchases
ON events.conference_id = purchases.conference_id
AND events.supportable = TRUE
AND purchases.finalized = TRUE
AND purchases.user_id = '#{current_user.id}'
")

      respond_to { |format| format.html }
    end
  end
end

app/controllers/frontend/block_controller.rb
module Frontend
  class BlockController < FrontendController
    before_action :authenticate_user!

    def create
      targetId = EventMessage.find(params[:id]).user_id
      if !Block.exists?(user_id: current_user.id, target: targetId)
        @block = Block.create(
            user_id: current_user.id,
            target: targetId
        )
      else
        head 409
      end
    end

    def getblocks
      render :json => Block.where(user_id: current_user.id)
    end

    def destroy
      block = Block.find(params[:id])
      if block.user_id == current_user.id
        block.destroy
        redirect_back(fallback_location: "/settings/blocks")
      else
        head 403
      end
    end

  end
end

app/controllers/frontend/conferences_controller.rb
module Frontend
  class ConferencesController < FrontendController
    SORT_PARAM = {
      'name' => 'title',
      'duration' => 'duration',
      'date' => 'date desc, release_date desc',
      'view_count' => 'view_count desc'
    }.freeze

    before_action :check_sort_param, only: %w(show)

    def all
      @conferences = conferences_with_events.order('event_last_released_at DESC')
      respond_to do |format|
        format.html { render :list }
      end
    end

    def browse
      return show if slug_matches_conference

      @folders = conferences_folder_tree_at(params[:slug] || '')
      return redirect_to root_url if @folders.blank?
      respond_to do |format|
        format.html { render :browse }
      end
    end

    def show
      @conference = Frontend::Conference.find_by!(acronym: params[:acronym]) unless @conference
      @events = @conference.events.includes(:conference).reorder(sort_param)
      respond_to do |format|
        format.html { render :show }
      end
    end

    private

    def slug_matches_conference
      @conference = Frontend::Conference.find_by(slug: params[:slug])
    end

    def conferences_folder_tree_at(path)
      tree = FolderTree.new
      tree.build(conferences_with_events.pluck(:id, :slug))
      folders = tree.folders_at(path)
      fail ActiveRecord::RecordNotFound unless folders
      tree.sort_folders(folders)
    end

    def conferences_with_events
      Conference.where('downloaded_events_count > 0')
    end

    def sort_param
      return SORT_PARAM[@sorting] if @sorting
      'view_count desc'
    end

    def check_sort_param
      return unless params[:sort]
      return unless SORT_PARAM.keys.include?(params[:sort])
      @sorting = params[:sort]
    end
  end
end

app/controllers/frontend/event_message_controller.rb
module Frontend
  class EventMessageController < FrontendController
    before_action :load_entities

    def create
      if current_user.muted_until == nil or current_user.muted_until < Time.zone.now
        @event_message = EventMessage.create(
          user: current_user,
          name: current_user.name,
          event: @event,
          message: params.dig(:event_message, :message))
        ActionCable.server.broadcast("event_#{@event.id}", @event_message)
      end
    end

    protected

    def load_entities
      @event = Event.find params.dig(:event_message, :event_id)
    end
  end
end

app/controllers/frontend/events_controller.rb
module Frontend
  class EventsController < FrontendController
    before_action :load_event
    before_action :store_location
    include ActionView::Helpers::NumberHelper

    def store_location
        session[:previous_url] = request.fullpath
    end

    def show
      respond_to { |format| format.html }
      @event_messages = @event.event_messages.includes(:user)
    end

    def playlist_related
      @playlist = Playlist.related(@event)
      respond_to { |format| format.html { render :playlist } }
    end

    def playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event)
      respond_to { |format| format.html { render :playlist } }
    end

    def audio_playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event, audio: true)
      respond_to { |format| format.html { render :playlist } }
    end

    def postroll
      @events = related_events(3)
      render layout: false
    end

    # videoplayer suitable for embedding in an iframe
    def oembed
      @width = params[:width] || view_context.aspect_ratio_width
      @height = params[:height] || view_context.aspect_ratio_height
      response.headers.delete 'X-Frame-Options'
      render layout: 'frontend/oembed'
    end

    private

    def related_events(n)
      return Event.find(@event.related_event_ids(n)) if @event.metadata['related'].present?
      @event.next_from_conference(n)
    end

    def load_event
      @event = Frontend::Event.find_by!(slug: params[:slug])
      @conference = @event.conference
    end
  end
end

app/controllers/frontend/group_event_controller.rb
module Frontend
  class GroupEventController < FrontendController
    before_action :load_event
    before_action :authenticate_user!

    def create
      orig_event_id = params.dig(:group_event, :event_id)
      source_event = Event.find(orig_event_id)
      new_event = GroupEvent.new(source_event.attributes.select{ |key, _| GroupEvent.attribute_names.include? key and !(%w(id, guid, created_at, updated_at).include? key)})
      date = Date.strptime(params.dig(:group_event, :date), "%d.%m.%Y")
      new_event.starting_time = Time.new(date.year, date.month, date.day, params.dig(:group_event, :hours), params.dig(:group_event, :minutes))
      new_event.join_code = SecureRandom.alphanumeric(9)
      new_event.synch_event = true
      new_event.original_event = orig_event_id
      new_event.slug = new_event.slug + "-" + new_event.join_code
      new_event.save

      GroupMember.create(event_id: new_event.id, user_id: current_user.id)

      render "/group_event"
    end

    def join
      code = params.dig(:group_event, :join_code).strip
      event = GroupEvent.find_by(join_code: code)
      if event.present?
        GroupMember.find_or_create_by(event_id: event.id, user_id: current_user.id)
      end
    end

    def load_event
      @event = GroupEvent.find_by!(slug: params[:slug])
    end

  end
end

app/controllers/frontend/home_controller.rb
module Frontend
  class HomeController < FrontendController
    helper_method :recent_events_for_conference
    CONFERENCE_LIMIT = 6
    EVENT_LIMIT = 3

    def index
      @news = Frontend::News.recent(1).first
      @hours_count = Frontend::Event.sum(:duration)/(60*60)
      @recordings_count = Frontend::Recording.count
      @events_count = Frontend::Event.count
      @conferences_count = Frontend::Conference.count
      @next_up = next_up

      @recent_conferences = Frontend::Conference.with_recent_events(CONFERENCE_LIMIT)

      respond_to { |format| format.html }
    end

    def next_up
      events = Frontend::Event.where("synch_event = true AND starting_time > NOW() - INTERVAL '3 hours'").order(starting_time: :asc).to_a
      events.delete_if{|event| event.event_over}
    end

    def page_not_found
      respond_to do |format|
        format.json { head :no_content }
        format.xml { render xml: { status: :error } }
        format.all { render :page_not_found, status: 404 }
      end
    end

    private

    def recent_events_for_conference(conference)
      conference.events.includes(:conference).limit(EVENT_LIMIT)
    end
  end
end

app/controllers/frontend/message_report_controller.rb
module Frontend
  class MessageReportController < FrontendController
    before_action :authenticate_user!
    def create
      @message_report = MessageReport.create(event_message: EventMessage.find(params[:id]));
    end
  end
end

app/controllers/frontend/moderation_controller.rb
module Frontend
  class ModerationController < ApplicationController
    before_action :authorize_admin

    def authorize_admin
      redirect_to root_path, alert: 'Access Denied' unless current_admin_user
    end

    def mute
      event_message = EventMessage.find(params[:id])
      user = event_message.user
      user.update_column(:mute_reason, params.dig(:user, :mute_reason))
      user.update_column(:muted_until, params.dig(:user, :muted_until))
      redirect_to "/admin/message_reports"
    end

    def mute_menu
      @event_message = EventMessage.find(params[:id])
      @user = @event_message.user
    end

    def unmute_menu
      user = User.find(params[:id])
      user.update_column(:muted_until, nil)
      redirect_to "/admin/users"
    end

    def context
      @context_messages = EventMessage.where("id < #{params[:id].to_i + 15} AND id > #{params[:id].to_i - 15} AND event_id = #{EventMessage.find(params[:id]).event_id}")
    end

    def delete
      report = MessageReport.find_by!(id: params[:id])
      MessageReport.where(event_message: report.event_message).destroy_all
      report.event_message.destroy
      redirect_back(fallback_location: "/admin/message_reports")
    end

    def approve
      report = MessageReport.find_by!(id: params[:id])
      MessageReport.where(event_message: report.event_message).destroy_all
      redirect_back(fallback_location: "/admin/message_reports")
    end
  end
end

app/controllers/frontend/news_controller.rb
module Frontend
  class NewsController < FrontendController
    def index
      news = News.latest_first
      atom_feed = Feeds::NewsFeedGenerator.generate(news,
        options: {
          author: Settings.feeds['channel_owner'],
          title: I18n.t('custom.news_title'),
          feed_url: news_url,
          icon: File.join(Settings.frontend_url, 'favicon.ico'),
          logo: view_context.image_url('frontend/voctocat.svg')
        })
      respond_to do |format|
        format.xml { render xml: atom_feed }
      end
    end
  end
end

app/controllers/frontend/popular_controller.rb
module Frontend
  class PopularController < FrontendController
    def index
      @events = Frontend::Event.order('view_count DESC').limit(20).includes(:conference)

      respond_to { |format| format.html }
    end

  end
end

app/views/frontend/events/_event.html.haml
- cache([event.conference, event]) do
  .event-preview
    = render partial: 'frontend/shared/event_thumb', locals: { event: event }
    = render partial: 'frontend/shared/event_metadata', locals: { event: event }

app/views/frontend/events/playlist.html.haml
- content_for :title do
  Playlist for
  = %("#{@playlist.title}")

- content_for :body_class do
  page-show

- cache([@playlist.playlist]) do
  .container-fluid
    .player-header
      - if @conference&.logo_url
        %a.thumbnail.conference{href: conference_path(acronym: @conference.acronym)}
          %img{src: @conference.logo_url, alt: 'conference logo'}
          - if @conference.logo_does_not_contain_title
            .caption
              = @conference.title
      - else 
        =@conference.title

      %h1
        Playlist
        = %("#{@playlist.title}")

    - if @playlist.audio?
      .player.audio
        = render partial: 'frontend/shared/player_playlist_audio', locals: { playlist: @playlist }

    - else
      .player.video
        .kiosk
        = render partial: 'frontend/shared/player_playlist_video', locals: video_player_ivars(playlist: @playlist)

    %h2.event_title
      = @playlist.lead_event.title
  
    %p.persons
      = render partial: 'frontend/shared/event_persons', locals: { persons: @playlist.lead_event.persons }
      
    %p
      = simple_format(@playlist.lead_event.description, class: :description)

app/views/frontend/events/postroll.html.haml
.postroll
  %h4 continue…
  .container-fluid
    .row
      .col-xs-12
        %b
          Related to
          - if @event.link
            = link_to @event.title, @event.link
          - else
            = @event.title

    .row
      - @events.each do |event|
        .col-xs-4.event
          = render partial: 'frontend/shared/event_title', locals: { event: event }
          = render partial: 'frontend/shared/event_thumb', locals: { event: event }

app/views/frontend/events/show.html.haml
- content_for :title do
  = @event.title

- content_for :body_class do
  page-show

- content_for :head do
  %meta{property: 'og:title', content: @event.title}
  %meta{property: 'og:type', content: 'video.other'}
  %meta{property: 'og:url', content: event_path(slug: @event.slug)}
  %meta{property: 'og:image', content: @event.poster_url}
  %meta{property: 'og:video', content: opengraph_video(@event.videos_sorted_by_language)}
  %meta{property: 'og:description', content: @event.short_description}
  != "<link href='#{oembed_api_event_url(@event)}' rel='alternate' title='media.ccc.de oembed profile' type='application/json+oembed'>"

- if current_admin_user
  - content_for :navbar do
    .nav.navbar-form.navbar-right.button-wrapper
      %a.form-control.btn.btn-default{href: edit_admin_event_path(@event)}
        %span.icon.icon-edit

- content_for :description do
  %meta{name: 'description', content: @event.short_description}

- cache([@event.conference, @event]) do

  - if @event.recordings.video.present?
    - if !@event.supportable or @event.view_threshold == 0 or (user_signed_in? and @event.user_purchased_view(current_user.id)) or @event.event_over
      - if @event.synch_event
        = render partial: 'frontend/shared/synch_event', locals: video_player_ivars
      - else
        .player
          .container-fluid
            = render partial: 'frontend/shared/player_video', locals: video_player_ivars
    - else
      .container-fluid
        =render partial: 'frontend/shared/buy', locals: video_player_ivars
  - else
    Keine Inhalte gefunden.
  .container-fluid
    %ul.metadata
      %li
        %span.icon.icon-clock-o
        = duration_in_minutes(@event.duration)
      %li
        %span.icon.icon-calendar-o{title: display_release_date_title(@event)}
        = @event.display_date
      - if ! @event.released_on_event_day?
        %li
          %span.icon.icon-upload{title: 'release date'}
          = @event.release_date
      %li
        %span.icon.icon-eye
        = @event.view_count
      - if @event.link.present?
        %li
          %span.icon.icon-external-link
          %a{href: @event.link}
            = parse_url_host(@event)

    .player-header
      .conference
        - if @conference&.logo_url
          %a.thumbnail.conference{href: conference_path(acronym: @conference.acronym)}
            %img{src: @conference.logo_url, alt: 'conference logo'}
            - if @conference.logo_does_not_contain_title
              .caption
                = @conference.title
        - else
          =@conference.title
      %h1
        = @event.title
      - unless @event.subtitle.blank?
        %h2
          = @event.subtitle

    %p.persons
      = render partial: 'frontend/shared/event_persons', locals: { persons: @event.persons }


    - if @event.description.present?
      /%h3 About
      %p.description
        = simple_format @event.description

    -if @event.downloadable and (@event.download_threshold == 0 or (user_signed_in? and @event.user_purchased_download(current_user.id)))
      %h3 Download
      .download
        = render partial: 'frontend/shared/download', locals: { conference: @conference, event: @event }

    -if @event.downloadable and user_signed_in? and @event.user_purchased_view(current_user.id) and !@event.user_purchased_download(current_user.id)
      %h3 Download
      .donate
        = render partial: 'frontend/shared/buy_download', locals: { conference: @conference, event: @event }

    -if @event.supportable and @event.view_threshold == 0
      %h3 Spenden
      .donate
        = render partial: 'frontend/shared/donate', locals: { conference: @conference, event: @event }

    - if @event.metadata['related'].present?
      %h3 Related
      = render partial: 'frontend/shared/related', locals: { events: Frontend::Event.find(@event.related_event_ids(10)) }

    /%h3 Embed/Share
    .share
      = render partial: 'frontend/shared/embedshare', locals: { event: @event }

    - if @event.tags.present?
      %h3 Tags
      .tags
        - @event.tags.each do |tag|
          != link_for(tag)