config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do
    resources :conferences, :defaults => { :format => 'json' }
    resources :events, :defaults => { :format => 'json' } do
      collection do
        post 'update_promoted'
        post 'update_view_counts'
      end
    end
    resources :recordings, :defaults => { :format => 'json' }
    resources :news, :defaults => { :format => 'json' }
  end

  namespace :public do
    get :index, path: '/', defaults: { format: 'json' }
    get :oembed
    resources :conferences, only: [:index, :show], defaults: { format: 'json' }
    constraints(id: %r'[^/]+') do
      resources :events, only: %i(index show), defaults: { format: 'json' } do
        get :search, defaults: { format: 'json' }, on: :collection
      end
    end
    resources :recordings, only: %i(index show), defaults: { format: 'json' } do
      collection do
        post 'count'
      end
    end
  end

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  get '/content/*path', to: 'content#load'

  scope module: 'frontend' do
    root to: 'home#index'
    if Rails.env.production?
      get '404', to: 'home#page_not_found'
    end
    get '/about', to: 'home#about'
    get '/impressum', to: 'home#impressum'
    get '/agb', to: 'home#agb'
    get '/datenschutz', to: 'home#datenschutz'
    get '/search', to: 'search#index'
    get '/sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

    get '/group_event', to: 'account#group'
    get '/library', to: 'account#library'
    get '/settings', to: 'account#settings'
    get '/settings/gdpr-download', to: 'account#gdpr_download'
    get '/settings/blocks', to: 'account#blocks'

    get '/v/:slug', to: 'events#show', as: :event, :constraints => { slug: %r'[^/]+' }
    get '/postroll/:slug', to: 'events#postroll', as: :postroll, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/playlist', to: 'events#playlist_conference', as: :playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/audio', to: 'events#audio_playlist_conference', as: :audio_playlist_conference, :constraints => { slug: %r'[^/]+' }
    get '/v/:slug/related', to: 'events#playlist_related', as: :playlist_related, :constraints => { slug: %r'[^/]+' }

    get '/g/:slug', to: 'group_event#show', :constraints => { slug: %r'[^/]+' }

    get '/c/:acronym', to: 'conferences#show', as: :conference

    get '/a', to: 'conferences#all', as: :all_conferences
    get '/b', to: 'conferences#browse', as: :browse_start
    get '/b/*slug', to: 'conferences#browse', as: :browse

    get '/recent', to: 'recent#index'
    get '/popular', to: 'popular#index'

    get '/tags/:tag', to: 'tags#show', as: :tag

    get '/purchase' => 'purchase#execute'

    get '/block' => 'block#getblocks'

    get '/moderation/:id/mute', to: 'moderation#mute_menu', as: :mute_menu, :constraints => { id: %r'[^/]+' }
    get '/moderation/:id/context', to: 'moderation#context', as: :context, :constraints => { id: %r'[^/]+' }
    match '/moderation/:id/unmute', to: 'moderation#unmute_menu', as: :unmute_menu, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/approve', to: 'moderation#approve', as: :approve, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/delete', to: 'moderation#delete', as: :delete, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/moderation/:id/mute', to: 'moderation#mute', as: :mute, :constraints => { id: %r'[^/]+' }, :via => :post
    match '/join_group', to: 'group_event#join', as: :join, :via => :post

    resources :event_message, :only => [:create]
    resources :purchase, :only => [:create]
    resources :message_report, :only => [:create]
    resources :block, :only => [:create, :destroy]
    resources :group_event, :only => [:create]

  end

end

app/controllers/frontend/account_controller.rb
module Frontend
  class AccountController < FrontendController
    before_action :authenticate_user!

    #GET /settings/blocks
    def blocks
      @blocks = Block.where(user_id: current_user.id)
      respond_to { |format| format.html }
    end

    #GET /settings/gdpr-download
    def gdpr_download
      send_data current_user.to_csv, filename: "#{current_user.name}-#{Date.today}.csv", :type => "text/csv", :disposition => "attachment"
    end

    #GET /library
    def library
      @events = Frontend::Event.joins("
INNER JOIN purchases
ON events.conference_id = purchases.conference_id
AND events.supportable = TRUE
AND purchases.finalized = TRUE
AND purchases.user_id = '#{current_user.id}'
")

      respond_to { |format| format.html }
    end
  end
end

app/controllers/frontend/block_controller.rb
module Frontend
  class BlockController < FrontendController
    before_action :authenticate_user!

    def create
      targetId = EventMessage.find(params[:id]).user_id
      if !Block.exists?(user_id: current_user.id, target: targetId)
        @block = Block.create(
            user_id: current_user.id,
            target: targetId
        )
      else
        head 409
      end
    end

    def getblocks
      render :json => Block.where(user_id: current_user.id)
    end

    def destroy
      block = Block.find(params[:id])
      if block.user_id == current_user.id
        block.destroy
        redirect_back(fallback_location: "/settings/blocks")
      else
        head 403
      end
    end

  end
end

app/controllers/frontend/conferences_controller.rb
module Frontend
  class ConferencesController < FrontendController
    SORT_PARAM = {
      'name' => 'title',
      'duration' => 'duration',
      'date' => 'date desc, release_date desc',
      'view_count' => 'view_count desc'
    }.freeze

    before_action :check_sort_param, only: %w(show)

    def all
      @conferences = conferences_with_events.order('event_last_released_at DESC')
      respond_to do |format|
        format.html { render :list }
      end
    end

    def browse
      return show if slug_matches_conference

      @folders = conferences_folder_tree_at(params[:slug] || '')
      return redirect_to root_url if @folders.blank?
      respond_to do |format|
        format.html { render :browse }
      end
    end

    def show
      @conference = Frontend::Conference.find_by!(acronym: params[:acronym]) unless @conference
      @events = @conference.events.includes(:conference).reorder(sort_param)
      respond_to do |format|
        format.html { render :show }
      end
    end

    private

    def slug_matches_conference
      @conference = Frontend::Conference.find_by(slug: params[:slug])
    end

    def conferences_folder_tree_at(path)
      tree = FolderTree.new
      tree.build(conferences_with_events.pluck(:id, :slug))
      folders = tree.folders_at(path)
      fail ActiveRecord::RecordNotFound unless folders
      tree.sort_folders(folders)
    end

    def conferences_with_events
      Conference.where('downloaded_events_count > 0')
    end

    def sort_param
      return SORT_PARAM[@sorting] if @sorting
      'view_count desc'
    end

    def check_sort_param
      return unless params[:sort]
      return unless SORT_PARAM.keys.include?(params[:sort])
      @sorting = params[:sort]
    end
  end
end

app/controllers/frontend/event_message_controller.rb
module Frontend
  class EventMessageController < FrontendController
    before_action :load_entities

    def create
      if current_user.muted_until == nil or current_user.muted_until < Time.zone.now
        @event_message = EventMessage.create(
          user: current_user,
          name: current_user.name,
          event: @event,
          message: params.dig(:event_message, :message))
        ActionCable.server.broadcast("event_#{@event.id}", @event_message)
      end
    end

    protected

    def load_entities
      @event = Event.find params.dig(:event_message, :event_id)
    end
  end
end

app/controllers/frontend/events_controller.rb
module Frontend
  class EventsController < FrontendController
    before_action :load_event
    before_action :store_location
    include ActionView::Helpers::NumberHelper

    def store_location
        session[:previous_url] = request.fullpath
    end

    def show
      respond_to { |format| format.html }
      @event_messages = @event.event_messages.includes(:user)
    end

    def playlist_related
      @playlist = Playlist.related(@event)
      respond_to { |format| format.html { render :playlist } }
    end

    def playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event)
      respond_to { |format| format.html { render :playlist } }
    end

    def audio_playlist_conference
      @playlist = Playlist.for_conference(@conference, lead_event: @event, audio: true)
      respond_to { |format| format.html { render :playlist } }
    end

    def postroll
      @events = related_events(3)
      render layout: false
    end

    # videoplayer suitable for embedding in an iframe
    def oembed
      @width = params[:width] || view_context.aspect_ratio_width
      @height = params[:height] || view_context.aspect_ratio_height
      response.headers.delete 'X-Frame-Options'
      render layout: 'frontend/oembed'
    end

    private

    def related_events(n)
      return Event.find(@event.related_event_ids(n)) if @event.metadata['related'].present?
      @event.next_from_conference(n)
    end

    def load_event
      @event = Frontend::Event.find_by!(slug: params[:slug])
      @conference = @event.conference
    end
  end
end

app/controllers/frontend/feeds_controller.rb
module Frontend
  class FeedsController < FrontendController
    before_action :set_conference, only: %i(podcast_folder)
    FEEDS_EXPIRY_DURATION = 15.minutes

    def podcast
      events_max_age = round_to_quarter_hour(Time.now.ago(2.years))

      xml = cache_fetch(:podcast, params[:quality], events_max_age.to_i) do
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: "recent events feed (#{FeedQuality.display_name(params[:quality])})",
          channel_summary: ' This feed contains events from the last two years',
          logo_image: logo_image_url
        )
        feed.generate(downloaded_events.newer(events_max_age)) do |event|
          EventRecordingFilter.by_quality_string(params[:quality]).filter(event)
        end
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_legacy
      events_max_age = round_to_quarter_hour(Time.now.ago(2.years))

      xml = cache_fetch(:podcast_legacy, events_max_age.to_i) do
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: 'recent events feed',
          channel_summary: ' This feed contains events from the last two years',
          logo_image: logo_image_url
        )
        # Leave filter method like this to not change the results of the feed
        feed.generate(downloaded_events.newer(events_max_age), &:preferred_recording)
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_archive
      events_min_age = round_to_quarter_hour(Time.now.ago(2.years))

      xml = cache_fetch(:podcast_archive, params[:quality], events_min_age.to_i) do
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: "archive feed (#{FeedQuality.display_name(params[:quality])})",
          channel_summary: ' This feed contains events older than two years',
          logo_image: logo_image_url
        )
        feed.generate(downloaded_events.older(events_min_age)) do |event|
          EventRecordingFilter.by_quality_string(params[:quality]).filter(event)
        end
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_archive_legacy
      events_min_age = round_to_quarter_hour(Time.now.ago(2.years))

      xml = cache_fetch(:podcast_archive_legacy, events_min_age.to_i) do
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: 'archive feed',
          channel_summary: ' This feed contains events older than two years',
          logo_image: logo_image_url
        )
        feed.generate(downloaded_events.older(events_min_age), &:preferred_recording)
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_folder
      xml = cache_fetch(:podcast_folder, params[:quality], @conference, @mime_type) do

        mime_display_name = MimeType.humanized_mime_type(@mime_type)
        quality_display_name = FeedQuality.display_name(params[:quality])
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: "#{@conference.title} (#{[quality_display_name, mime_display_name].reject(&:empty?).join(' ')})",
          channel_summary: " This feed contains all events from #{@conference.acronym} as #{mime_display_name}",
          channel_description: " This feed contains all events from #{@conference.acronym} as #{mime_display_name}",
          base_url: view_context.conference_url(acronym: @conference.acronym),
          logo_image: @conference.logo_url
        )
        feed.generate(@conference.events.includes(:conference)) do |event|
          EventRecordingFilter
            .by_quality_string(params[:quality])
            .with_mime_type(@mime_type)
            .filter(event)
        end
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    def podcast_audio
      events_max_age = round_to_quarter_hour(Time.now.ago(1.years))
      xml = cache_fetch(:podcast_audio, events_max_age.to_i) do
        feed = Feeds::PodcastGenerator.new(
          view_context,
          title: 'recent audio-only feed',
          channel_summary: ' This feed contains audio files from the last year',
          logo_image: logo_image_url
        )
        feed.generate(downloaded_events.newer(events_max_age), &:audio_recording)
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    # rss 1.0 last 100 feed
    def updates
      xml = cache_fetch(:rdftop100) do
        events = downloaded_events.recent(100)
        feed = Feeds::RDFGenerator.new(
          view_context: view_context,
          config: {
             title: 'last 100 events feed',
             channel_summary: ' This feed the most recent 100 events',
             logo: logo_image_url
          }
        )
        feed.generate events
      end
      respond_to do |format|
        format.xml { render xml: xml }
      end
    end

    private

    def cache_fetch(*key)
      Rails.cache.fetch(key, expires_in: FEEDS_EXPIRY_DURATION) do
        yield if block_given?
      end
    end

    def downloaded_events
      Frontend::Event.includes(:conference)
    end

    def logo_image_url
      view_context.image_url('frontend/feed-banner.png')
    end

    def round_to_quarter_hour(time)
      seconds = 15 * 60
      Time.at((time.to_f / seconds).floor * seconds)
    end

    def set_conference
      @conference = if params[:acronym]
                      Frontend::Conference.find_by!(acronym: params[:acronym])
                    elsif params[:slug]
                      Frontend::Conference.find_by!(slug: params[:slug])
                    end
      fail ActiveRecord::RecordNotFound unless @conference

      @mime_type, @mime_type_name = @conference.mime_types.find { |_m, n| n == params[:mime_type] }
      fail ActiveRecord::RecordNotFound unless @mime_type
    end
  end
end

app/controllers/frontend/group_event_controller.rb
module Frontend
  class GroupEventController < FrontendController
    before_action :load_event
    before_action :authenticate_user!

    def create
      orig_event_id = params.dig(:group_event, :event_id)
      source_event = Event.find(orig_event_id)
      new_event = GroupEvent.new(source_event.attributes.select{ |key, _| GroupEvent.attribute_names.include? key and !(%w(id, guid, created_at, updated_at).include? key)})
      date = Date.strptime(params.dig(:group_event, :date), "%d.%m.%Y")
      new_event.starting_time = Time.new(date.year, date.month, date.day, params.dig(:group_event, :hours), params.dig(:group_event, :minutes))
      new_event.join_code = SecureRandom.alphanumeric(9)
      new_event.synch_event = true
      new_event.original_event = orig_event_id
      new_event.slug = new_event.slug + "-" + new_event.join_code
      new_event.save

      GroupMember.create(event_id: new_event.id, user_id: current_user.id)

      render "/group_event"
    end

    def join
      code = params.dig(:group_event, :join_code).strip
      event = GroupEvent.find_by(join_code: code)
      if event.present?
        GroupMember.find_or_create_by(event_id: event.id, user_id: current_user.id)
      end
    end

    def load_event
      @event = GroupEvent.find_by!(slug: params[:slug])
    end

  end
end

app/controllers/frontend/message_report_controller.rb
module Frontend
  class MessageReportController < FrontendController
    before_action :authenticate_user!
    def create
      @message_report = MessageReport.create(event_message: EventMessage.find(params[:id]));
    end
  end
end

app/controllers/frontend/popular_controller.rb
module Frontend
  class PopularController < FrontendController
    def index
      @events = Frontend::Event.order('view_count DESC').limit(20).includes(:conference)

      respond_to { |format| format.html }
    end

  end
end

app/views/frontend/account/blocks.html.haml
- content_for :title do
  Meine Blockierungen

- content_for :body_class do
  page-list

.container-fluid
  %h1 Meine Blocks
  - if @blocks.present?
    .event-previews
      - @blocks.each do |block|
        %h3
          = User.find(block.target).name
        %p
          -if ArchivedName.where(user_id: block.target).exists?
            Weitere Namen:
            - ArchivedName.where(user_id: block.target).each do |archived_name|
              %br/
              \-&nbsp;
              %i
                = archived_name.name
        =form_for(:block, url: "/block/#{block.id}", method: "delete") do |f|
          =f.submit "Entblocken"
        %br
  - else
    %h3 Du hast zur Zeit keine Nutzer*innen blockiert.

app/views/frontend/account/group.html.haml
- content_for :title do
  Filmabend

- content_for :body_class do
  page-list

.container-fluid
  %h1 Filmabend
  =# TODO HÜBSCHES BILD
  %h2 Ausstehend
  %ul.list-unstyled
    - GroupMember.where(user_id: current_user.id).each do |member|
      = render partial: 'frontend/shared/group_event_thumb', locals: { event: member.get_event}
  %h2 Beitreten
  %p Um einem Filmabend beizutreten benötigst du das Codewort, welches die Person die den Filmabend erstellt hat festgelegt hat.
  = form_for(:group_event, :url => "/join_group", html: { method: :post, autocomplete: "off"}) do |f|
    .field
      = f.label "Codewort"
      &nbsp;
      = f.text_field :join_code
    .actions
      %br/
      = f.submit "Beitreten"
  %h2 Erstellen
  = form_for(:group_event, :url => "/group_event", html: { method: :post, autocomplete: "off"}) do |f|
    .field
      %p
        = f.label "Film"
        &nbsp;
        = f.select :event_id, Event.pluck(:title, :id)
      %p
        = f.label "Datum"
        &nbsp;
        = f.text_field :date, {"data-provide": 'datepicker', "data-date-language": "de"}
      %p
        = f.label "Uhrzeit"
        &nbsp;
        = f.select :hour, %w(00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23)
        \:
        = f.select :minute, %w(00 05 10 15 20 25 30 35 40 45 50 55)
    .actions
      %br/
      = f.submit "Erstellen"

app/views/frontend/account/library.html.haml
- content_for :title do
  Bibliothek

- content_for :body_class do
  page-list

.container-fluid
  %h1 Meine Bibliothek
  %p Hier findest du alle Inhalte die du erworben oder mit einer Spende unterstützt hast.
  - if @events.present?
    .event-previews
      - @events.each do |event|
        = render partial: 'frontend/shared/event_with_conference', locals: { event: event }

app/views/frontend/account/settings.html.haml
= javascript_include_tag 'confirmation.js'

- content_for :title do
  Einstellungen

.container
  %br/
  %img{src: image_path('frontend/ginsterkatze.jpg'), alt: 'An old drawing of a genet', width: '50%', style: "float:right"}
  %h2
    Einstellungen

  %h3 Chat
  = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
    .field
      = f.label "Nickname"
      %br/
      = f.text_field :name, input_html: { value: nil}
    %br/
    .actions
      = f.submit "Update"
    %br/
    Aktueller Nickname:
    %i #{current_user.name}
    %br/
    %br/
    %b Stummschaltung
    %br/
    -if current_user.muted_until != nil and current_user.muted_until > Time.zone.now
      Du bist bis zum #{current_user.muted_until.to_formatted_s(:date_german)} stumm geschaltet.
      %br/
      Begründung:
      %i
        #{current_user.mute_reason}
      %br/
      Bitte halte dich in Zukunft an die Community-Regeln.
    -else
      Du bist aktuell nicht stumm geschaltet.
      %br/
      Danke, dass du die Community-Regeln respektierst.
    %br/
    %br/
    %b Blocks
    %br/
    Du hast zur Zeit
    = link_to Block.where(user_id: current_user.id).count.to_s + " Nutzer*innen", "/settings/blocks"
    blockiert.
  %h3 Daten ändern
  = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
    = render "devise/shared/error_messages", resource: resource
    .field
      = f.label :email
      %br/
      = f.email_field :email, autocomplete: "email"
    - if devise_mapping.confirmable? && resource.pending_reconfirmation?
      %div
        Warte auf Bestätigung für: #{resource.unconfirmed_email}
    %br/
    .field
      %b Neues Passwort
      %i (Wenn du nur deine E-Mail Adresse ändern willst lasse das Feld einfach frei)
      %br/
      = f.password_field :password, autocomplete: "new-password"
      - if @minimum_password_length
        %br/
        %em
          = @minimum_password_length
          characters minimum
    %br/
    .field
      %b Bestätigung des neuen Passworts
      %br/
      = f.password_field :password_confirmation, autocomplete: "new-password"
    %br/
    .field
      %b Aktuelles Passwort
      %i (Um Änderungen durchzuführen benötigen wir dein aktuelles Passwort)
      %br/
      = f.password_field :current_password, autocomplete: "current-password"
    %br/
    .actions
      = f.submit "Update"
  %h3 Daten herunterladen
  %p Das speichern wir über dich:
  %ol
    %li Deine E-Mail Adresse
    %li Deine verwendeten Nicknames
    %li Einen Hashwert deines Passworts
    %li Eine Liste der Medien die du gekauft oder geliehen hast
    %li Einen Hinweis ob und bis wann du stumm geschaltet bist
  %p
    = link_to "Meine Daten herunterladen", "/settings/gdpr-download"

  %h3 Account löschen
  .deletionwarning
    %p Achtung! Dies kann nicht rückgängig gemacht werden! Sofern du sie nicht heruntergeladen hast verlierst du den Zugang zu allen gekauften Filmen.
    %p Um die Löschung zu bestätigen schreibe "Wirklich löschen!" in das Textfeld, gebe dein Passwort ein und drücke den Knopf.
    %p
      %b Bestätigung
    %p
      = text_field_tag "confirmation", "", id: "user_confirmation"
    %p
      = form_for(:user, :url => registration_path(resource_name), html: { method: :delete }) do |f|
        .field
          = f.label "Passwort"
          %br/
          = f.password_field :current_password, autocomplete: "current-password"
          %br/
          %br/
        .actions
          = f.submit "Löschen" , {id: "delete"}